name = ["apple", "grapes","orange", "banana" ]
name
type(name)
dir(name)
name.append("orange")
name.clear()
nam2 = name.copy()
nam2
name.extend(["gauva","pineapple"])
name.index("banana")
name.insert(2,"mango")
name.pop(2)
name.remove(3)
name.reverse()
name.sort(reverse=True)
list2 = name.copy()
id(list2)
id(name)
str1 = "hello wOrLd"
dir(str1)
str1.capitalize()
str1.zfill(12)
str1.index("and")
str1.find("and")
str1.isalnum()
str1.join("helloworld")
str1.replace("hello", "hii")
str1.ljust(21,"q")
str1.split(" ")
str1.swapcase()
str1.strip()
str1.center(20,"t")
set1 = {1,2,3,4,5,6}
set2 = {2,3,4,0}
set1.update([5])
set1.symmetric_difference(set2)
set1.isdisjoint(set2)
set2.issubset(set1)
set1.issuperset(set2)